In [187]:
import pandas as pd
df = pd.read_csv("CWC Schedule.csv")
df

,Subject,Start Date,Start Time,End Date,End Time,All Day Event,Description,Location
0,New Zealand VS Sri Lanka,14/02/2015,9:00 AM,14/02/2015,5:00 PM,False,"Match 1 , Pool A",Christchurch
1,Australia VS England,14/02/2015,2:30 PM,14/02/2015,10:30 PM,False,"Match 2 , Pool A",MCG
2,South Africa VS Zimbabwe,15/02/2015,12:00 PM,15/02/2015,8:00 PM,False,"Match 3 , Pool B",Hamilton
3,India VS Pakistan,15/02/2015,2:30 PM,15/02/2015,10:30 PM,False,"Match 4 , Pool B",Adelaide
4,Ireland VS West Indies,16/02/2015,9:00 AM,16/02/2015,5:00 PM,False,"Match 5 , Pool B",Nelson
5,New Zealand VS Scotland,17/02/2015,9:00 AM,17/02/2015,5:00 PM,False,"Match 6 , Pool A",Dunedin
6,Afghanistan VS Bangladesh,18/02/2015,2:30 PM,18/02/2015,10:30 PM,False,"Match 7 , Pool A",Canberra
7,UAE VS Zimbabwe,19/02/2015,9:00 AM,19/02/2015,5:00 PM,False,"Match 8 , Pool B",Nelson
8,New Zealand VS England,20/02/2015,12:00 PM,20/02/2015,8:00 PM,False,"Match 9 , Pool A",Wellington
9,Pakistan VS West Indies,21/02/2015,9:00 AM,21/02/2015,5:00 PM,False,"Match 10 , Pool B",Christchurch
10,Australia VS Bangladesh,21/02/2015,2:30 PM,21/02/2015,10:30 PM,False,"Match 11 , Pool A",Brisbane
11,Afghanistan VS Sri Lanka,22/02/2015,9:00 AM,22/02/2015,5:00 PM,False,"Match 12 , Pool A",Dunedin
12,India VS South Africa,22/02/2015,2:30 PM,22/02/2015,10:30 PM,False,"Match 13 , Pool B",MCG
13,England VS Scotland,23/02/2015,9:00 AM,23/02/2015,5:00 PM,False,"Match 14 , Pool A",Christchurch
14,West Indies VS Zimbabwe,24/02/2015,2:30 PM,24/02/2015,10:30 PM,False,"Match 15 , Pool B",Canberra
15,Ireland VS UAE,25/02/2015,2:30 PM,25/02/2015,10:30 PM,False,"Match 16 , Pool B",Brisbane
16,Afghanistan VS Scotland,26/02/2015,9:00 AM,26/02/2015,5:00 PM,False,"Match 17 , Pool A",Dunedin
17,Bangladesh VS Sri Lanka,26/02/2015,2:30 PM,26/02/2015,10:30 PM,False,"Match 18 , Pool A",MCG
18,South Africa VS West Indies,27/02/2015,2:30 PM,27/02/2015,10:30 PM,False,"Match 19 , Pool B",SCG
19,New Zealand VS Australia,28/02/2015,12:00 PM,28/02/2015,8:00 PM,False,"Match 20 , Pool B",Auckland
20,India VS UAE,28/02/2015,5:30 PM,28/02/2015,1:30 AM,False,"Match 21 , Pool B",Perth
21,England VS Sri Lanka,1/03/2015,9:00 AM,1/03/2015,5:00 PM,False,"Match 22 , Pool A",Wellington
22,Pakistan VS Zimbabwe,1/03/2015,2:30 PM,1/03/2015,10:30 PM,False,"Match 23 , Pool B",Brisbane
23,Ireland VS South Africa,3/03/2015,2:30 PM,3/03/2015,10:30 PM,False,"Match 24 , Pool B",Canberra
24,Pakistan VS UAE,4/03/2015,12:00 PM,4/03/2015,8:00 PM,False,"Match 25 , Pool B",Napier
25,Australia VS Afghanistan,4/03/2015,5:30 PM,4/03/2015,1:30 AM,False,"Match 26 , Pool A",Perth
26,Bangladesh VS Scotland,5/03/2015,9:00 AM,5/03/2015,5:00 PM,False,"Match 27 , Pool A",Nelson
27,India VS West Indies,6/03/2015,5:30 PM,6/03/2015,1:30 AM,False,"Match 28 , Pool B",Perth
28,Pakistan VS South Africa,7/03/2015,12:00 PM,7/03/2015,8:00 PM,False,"Match 29 , Pool B",Auckland
29,Ireland VS Zimbabwe,7/03/2015,2:30 PM,7/03/2015,10:30 PM,False,"Match 30 , Pool B",Hobart
30,New Zealand VS Afghanistan,8/03/2015,9:00 AM,8/03/2015,5:00 PM,False,"Match 31 , Pool A",Napier
31,Australia VS Sri Lanka,8/03/2015,2:30 PM,8/03/2015,10:30 PM,False,"Match 32 , Pool A",SCG
32,England VS Bangladesh,9/03/2015,2:30 PM,9/03/2015,10:30 PM,False,"Match 33 , Pool A",Adelaide
33,India VS Ireland,10/03/2015,12:00 PM,10/03/2015,8:00 PM,False,"Match 34 , Pool B",Hamilton
34,Scotland VS Sri Lanka,11/03/2015,2:30 PM,11/03/2015,10:30 PM,False,"Match 35 , Pool A",Hobart
35,South Africa VS UAE,12/03/2015,12:00 PM,12/03/2015,8:00 PM,False,"Match 36 , Pool B",Wellington
36,New Zealand VS Bangladesh,13/03/2015,12:00 PM,13/03/2015,8:00 PM,False,"Match 37 , Pool A",Hamilton
37,Afghanistan VS England,13/03/2015,2:30 PM,13/03/2015,10:30 PM,False,"Match 38 , Pool A",SCG
38,India VS Zimbabwe,14/03/2015,12:00 PM,14/03/2015,8:00 PM,False,"Match 39 , Pool B",Auckland
39,Australia VS Scotland,14/03/2015,2:30 PM,14/03/2015,10:30 PM,False,"Match 40 , Pool A",Hobart
40,UAE VS West Indies,15/03/2015,9:00 AM,15/03/2015,5:00 PM,False,"Match 41 , Pool B",Napier
41,Ireland VS Pakistan,15/03/2015,2:30 PM,15/03/2015,10:30 PM,False,"Match 42 , Pool B",Adelaide
42,Quarter Final 1,18/03/2015,2:30 PM,18/03/2015,10:30 PM,False,NaN,SCG
43,Quarter Final 2,19/03/2015,2:30 PM,19/03/2015,10:30 PM,False,NaN,MCG
44,Quarter Final 3,20/03/2015,2:30 PM,20/03/2015,10:30 PM,False,NaN,Adelaide
45,Quarter Final 4,21/03/2015,12:00 PM,21/03/2015,8:00 PM,False,NaN,Wellington
46,Semi Final 1,24/03/2015,12:00 PM,24/03/2015,8:00 PM,False,NaN,Auckland
47,Semi Final 2,26/03/2015,2:30 PM,26/03/2015,10:30 PM,False,NaN,SCG
48,Final,29/03/2015,2:30 PM,29/03/2015,10:30 PM,False,NaN,MCG

In [188]:
def left(subj):
    marker = subj.find("VS")
    if marker != -1:
        a = subj[0:marker-1]
        return a
    
def right(subj):
    marker = subj.find("VS")
    if marker != -1:
        b = subj[marker+3:len(subj)]
        return b

df['teamA'] = df.Subject.apply(left)
df['teamB'] = df.Subject.map(right)
df['AWin'] = [2,2,2,2,2,2,0,0,2,0,1,0,2,2,2,2,2,0,2,2,2,0,2,0,2,2,2,2,2,2,2,2,0,2,0,2,2,0,2,2,0,0,3,3,3,3,3,3,4]
df['winner'] = df.teamA
df.winner[df.AWin == 0] = df.teamB
df

,Subject,Start Date,Start Time,End Date,End Time,All Day Event,Description,Location,teamA,teamB,AWin,winner
0,New Zealand VS Sri Lanka,14/02/2015,9:00 AM,14/02/2015,5:00 PM,False,"Match 1 , Pool A",Christchurch,New Zealand,Sri Lanka,2,New Zealand
1,Australia VS England,14/02/2015,2:30 PM,14/02/2015,10:30 PM,False,"Match 2 , Pool A",MCG,Australia,England,2,Australia
2,South Africa VS Zimbabwe,15/02/2015,12:00 PM,15/02/2015,8:00 PM,False,"Match 3 , Pool B",Hamilton,South Africa,Zimbabwe,2,South Africa
3,India VS Pakistan,15/02/2015,2:30 PM,15/02/2015,10:30 PM,False,"Match 4 , Pool B",Adelaide,India,Pakistan,2,India
4,Ireland VS West Indies,16/02/2015,9:00 AM,16/02/2015,5:00 PM,False,"Match 5 , Pool B",Nelson,Ireland,West Indies,2,Ireland
5,New Zealand VS Scotland,17/02/2015,9:00 AM,17/02/2015,5:00 PM,False,"Match 6 , Pool A",Dunedin,New Zealand,Scotland,2,New Zealand
6,Afghanistan VS Bangladesh,18/02/2015,2:30 PM,18/02/2015,10:30 PM,False,"Match 7 , Pool A",Canberra,Afghanistan,Bangladesh,0,Bangladesh
7,UAE VS Zimbabwe,19/02/2015,9:00 AM,19/02/2015,5:00 PM,False,"Match 8 , Pool B",Nelson,UAE,Zimbabwe,0,Zimbabwe
8,New Zealand VS England,20/02/2015,12:00 PM,20/02/2015,8:00 PM,False,"Match 9 , Pool A",Wellington,New Zealand,England,2,New Zealand
9,Pakistan VS West Indies,21/02/2015,9:00 AM,21/02/2015,5:00 PM,False,"Match 10 , Pool B",Christchurch,Pakistan,West Indies,0,West Indies
10,Australia VS Bangladesh,21/02/2015,2:30 PM,21/02/2015,10:30 PM,False,"Match 11 , Pool A",Brisbane,Australia,Bangladesh,1,Australia
11,Afghanistan VS Sri Lanka,22/02/2015,9:00 AM,22/02/2015,5:00 PM,False,"Match 12 , Pool A",Dunedin,Afghanistan,Sri Lanka,0,Sri Lanka
12,India VS South Africa,22/02/2015,2:30 PM,22/02/2015,10:30 PM,False,"Match 13 , Pool B",MCG,India,South Africa,2,India
13,England VS Scotland,23/02/2015,9:00 AM,23/02/2015,5:00 PM,False,"Match 14 , Pool A",Christchurch,England,Scotland,2,England
14,West Indies VS Zimbabwe,24/02/2015,2:30 PM,24/02/2015,10:30 PM,False,"Match 15 , Pool B",Canberra,West Indies,Zimbabwe,2,West Indies
15,Ireland VS UAE,25/02/2015,2:30 PM,25/02/2015,10:30 PM,False,"Match 16 , Pool B",Brisbane,Ireland,UAE,2,Ireland
16,Afghanistan VS Scotland,26/02/2015,9:00 AM,26/02/2015,5:00 PM,False,"Match 17 , Pool A",Dunedin,Afghanistan,Scotland,2,Afghanistan
17,Bangladesh VS Sri Lanka,26/02/2015,2:30 PM,26/02/2015,10:30 PM,False,"Match 18 , Pool A",MCG,Bangladesh,Sri Lanka,0,Sri Lanka
18,South Africa VS West Indies,27/02/2015,2:30 PM,27/02/2015,10:30 PM,False,"Match 19 , Pool B",SCG,South Africa,West Indies,2,South Africa
19,New Zealand VS Australia,28/02/2015,12:00 PM,28/02/2015,8:00 PM,False,"Match 20 , Pool B",Auckland,New Zealand,Australia,2,New Zealand
20,India VS UAE,28/02/2015,5:30 PM,28/02/2015,1:30 AM,False,"Match 21 , Pool B",Perth,India,UAE,2,India
21,England VS Sri Lanka,1/03/2015,9:00 AM,1/03/2015,5:00 PM,False,"Match 22 , Pool A",Wellington,England,Sri Lanka,0,Sri Lanka
22,Pakistan VS Zimbabwe,1/03/2015,2:30 PM,1/03/2015,10:30 PM,False,"Match 23 , Pool B",Brisbane,Pakistan,Zimbabwe,2,Pakistan
23,Ireland VS South Africa,3/03/2015,2:30 PM,3/03/2015,10:30 PM,False,"Match 24 , Pool B",Canberra,Ireland,South Africa,0,South Africa
24,Pakistan VS UAE,4/03/2015,12:00 PM,4/03/2015,8:00 PM,False,"Match 25 , Pool B",Napier,Pakistan,UAE,2,Pakistan
25,Australia VS Afghanistan,4/03/2015,5:30 PM,4/03/2015,1:30 AM,False,"Match 26 , Pool A",Perth,Australia,Afghanistan,2,Australia
26,Bangladesh VS Scotland,5/03/2015,9:00 AM,5/03/2015,5:00 PM,False,"Match 27 , Pool A",Nelson,Bangladesh,Scotland,2,Bangladesh
27,India VS West Indies,6/03/2015,5:30 PM,6/03/2015,1:30 AM,False,"Match 28 , Pool B",Perth,India,West Indies,2,India
28,Pakistan VS South Africa,7/03/2015,12:00 PM,7/03/2015,8:00 PM,False,"Match 29 , Pool B",Auckland,Pakistan,South Africa,2,Pakistan
29,Ireland VS Zimbabwe,7/03/2015,2:30 PM,7/03/2015,10:30 PM,False,"Match 30 , Pool B",Hobart,Ireland,Zimbabwe,2,Ireland
30,New Zealand VS Afghanistan,8/03/2015,9:00 AM,8/03/2015,5:00 PM,False,"Match 31 , Pool A",Napier,New Zealand,Afghanistan,2,New Zealand
31,Australia VS Sri Lanka,8/03/2015,2:30 PM,8/03/2015,10:30 PM,False,"Match 32 , Pool A",SCG,Australia,Sri Lanka,2,Australia
32,England VS Bangladesh,9/03/2015,2:30 PM,9/03/2015,10:30 PM,False,"Match 33 , Pool A",Adelaide,England,Bangladesh,0,Bangladesh
33,India VS Ireland,10/03/2015,12:00 PM,10/03/2015,8:00 PM,False,"Match 34 , Pool B",Hamilton,India,Ireland,2,India
34,Scotland VS Sri Lanka,11/03/2015,2:30 PM,11/03/2015,10:30 PM,False,"Match 35 , Pool A",Hobart,Scotland,Sri Lanka,0,Sri Lanka
35,South Africa VS UAE,12/03/2015,12:00 PM,12/03/2015,8:00 PM,False,"Match 36 , Pool B",Wellington,South Africa,UAE,2,South Africa
36,New Zealand VS Bangladesh,13/03/2015,12:00 PM,13/03/2015,8:00 PM,False,"Match 37 , Pool A",Hamilton,New Zealand,Bangladesh,2,New Zealand
37,Afghanistan VS England,13/03/2015,2:30 PM,13/03/2015,10:30 PM,False,"Match 38 , Pool A",SCG,Afghanistan,England,0,England
38,India VS Zimbabwe,14/03/2015,12:00 PM,14/03/2015,8:00 PM,False,"Match 39 , Pool B",Auckland,India,Zimbabwe,2,India
39,Australia VS Scotland,14/03/2015,2:30 PM,14/03/2015,10:30 PM,False,"Match 40 , Pool A",Hobart,Australia,Scotland,2,Australia
40,UAE VS West Indies,15/03/2015,9:00 AM,15/03/2015,5:00 PM,False,"Match 41 , Pool B",Napier,UAE,West Indies,0,West Indies
41,Ireland VS Pakistan,15/03/2015,2:30 PM,15/03/2015,10:30 PM,False,"Match 42 , Pool B",Adelaide,Ireland,Pakistan,0,Pakistan
42,Quarter Final 1,18/03/2015,2:30 PM,18/03/2015,10:30 PM,False,NaN,SCG,None,None,3,None
43,Quarter Final 2,19/03/2015,2:30 PM,19/03/2015,10:30 PM,False,NaN,MCG,None,None,3,None
44,Quarter Final 3,20/03/2015,2:30 PM,20/03/2015,10:30 PM,False,NaN,Adelaide,None,None,3,None
45,Quarter Final 4,21/03/2015,12:00 PM,21/03/2015,8:00 PM,False,NaN,Wellington,None,None,3,None
46,Semi Final 1,24/03/2015,12:00 PM,24/03/2015,8:00 PM,False,NaN,Auckland,None,None,3,None
47,Semi Final 2,26/03/2015,2:30 PM,26/03/2015,10:30 PM,False,NaN,SCG,None,None,3,None
48,Final,29/03/2015,2:30 PM,29/03/2015,10:30 PM,False,NaN,MCG,None,None,4,None

In [193]:
melted = pd.melt(df, id_vars = ['winner', 'Start Date'], value_vars = 'AWin', var_name = 'Owner', value_name = 'Pts')
melted.Pts[melted.Pts == 0] = 2

tie = pd.Series(['Bangladesh', '21/02/2015', 'AWin', 1], index = ['winner', 'Start Date', 'Owner', 'Pts'])
last = pd.DataFrame({
                    'winner': ['Australia','New Zealand','India','South Africa'],
                    'Start Date': ['29/03/2015']*4,
                    'Owner': ['Ashley', 'David', 'Jeff', 'Raghav'],
                    'Pts': [0]*4})

melted2 = melted.append(tie, ignore_index = True)
melted2 = melted2.append(last, ignore_index = True)
melted2.winner.loc[42:48] = ['South Africa', 'Australia', 'India', 'New Zealand', 'New Zealand', 'Australia', '?']

melted2

     Owner  Pts  Start Date        winner
0     AWin    2  14/02/2015   New Zealand
1     AWin    2  14/02/2015     Australia
2     AWin    2  15/02/2015  South Africa
3     AWin    2  15/02/2015         India
4     AWin    2  16/02/2015       Ireland
5     AWin    2  17/02/2015   New Zealand
6     AWin    2  18/02/2015    Bangladesh
7     AWin    2  19/02/2015      Zimbabwe
8     AWin    2  20/02/2015   New Zealand
9     AWin    2  21/02/2015   West Indies
10    AWin    1  21/02/2015     Australia
11    AWin    2  22/02/2015     Sri Lanka
12    AWin    2  22/02/2015         India
13    AWin    2  23/02/2015       England
14    AWin    2  24/02/2015   West Indies
15    AWin    2  25/02/2015       Ireland
16    AWin    2  26/02/2015   Afghanistan
17    AWin    2  26/02/2015     Sri Lanka
18    AWin    2  27/02/2015  South Africa
19    AWin    2  28/02/2015   New Zealand
20    AWin    2  28/02/2015         India
21    AWin    2   1/03/2015     Sri Lanka
22    AWin    2   1/03/2015      Pakistan
23    AWin    2   3/03/2015  South Africa
24    AWin    2   4/03/2015      Pakistan
25    AWin    2   4/03/2015     Australia
26    AWin    2   5/03/2015    Bangladesh
27    AWin    2   6/03/2015         India
28    AWin    2   7/03/2015      Pakistan
29    AWin    2   7/03/2015       Ireland
30    AWin    2   8/03/2015   New Zealand
31    AWin    2   8/03/2015     Australia
32    AWin    2   9/03/2015    Bangladesh
33    AWin    2  10/03/2015         India
34    AWin    2  11/03/2015     Sri Lanka
35    AWin    2  12/03/2015  South Africa
36    AWin    2  13/03/2015   New Zealand
37    AWin    2  13/03/2015       England
38    AWin    2  14/03/2015         India
39    AWin    2  14/03/2015     Australia
40    AWin    2  15/03/2015   West Indies
41    AWin    2  15/03/2015      Pakistan
42    AWin    3  18/03/2015  South Africa
43    AWin    3  19/03/2015     Australia
44    AWin    3  20/03/2015         India
45    AWin    3  21/03/2015   New Zealand
46    AWin    3  24/03/2015   New Zealand
47    AWin    3  26/03/2015     Australia
48    AWin    4  29/03/2015             ?
49    AWin    1  21/02/2015    Bangladesh
50  Ashley    0  29/03/2015     Australia
51   David    0  29/03/2015   New Zealand
52    Jeff    0  29/03/2015         India
53  Raghav    0  29/03/2015  South Africa

In [194]:
participants = {
                'Australia' : 'Ashley',
                'India': 'Jeff',
                'South Africa' : 'Raghav',
                'New Zealand' : 'David',
                'Pakistan' : 'David',
                'England' : 'Raghav',
                'Sri Lanka' : 'Jeff',
                'West Indies' : 'Ashley',
                'Ireland' : 'Ashley',
                'Bangladesh' : 'Jeff',
                'Scotland' : 'Raghav',
                'Zimbabwe' : 'David',
                'Afghanistan' : 'David',
                'UAE' : 'Raghav'
                }

melted2['Owner'] = melted2.winner.map(participants)
melted2

     Owner  Pts  Start Date        winner
0    David    2  14/02/2015   New Zealand
1   Ashley    2  14/02/2015     Australia
2   Raghav    2  15/02/2015  South Africa
3     Jeff    2  15/02/2015         India
4   Ashley    2  16/02/2015       Ireland
5    David    2  17/02/2015   New Zealand
6     Jeff    2  18/02/2015    Bangladesh
7    David    2  19/02/2015      Zimbabwe
8    David    2  20/02/2015   New Zealand
9   Ashley    2  21/02/2015   West Indies
10  Ashley    1  21/02/2015     Australia
11    Jeff    2  22/02/2015     Sri Lanka
12    Jeff    2  22/02/2015         India
13  Raghav    2  23/02/2015       England
14  Ashley    2  24/02/2015   West Indies
15  Ashley    2  25/02/2015       Ireland
16   David    2  26/02/2015   Afghanistan
17    Jeff    2  26/02/2015     Sri Lanka
18  Raghav    2  27/02/2015  South Africa
19   David    2  28/02/2015   New Zealand
20    Jeff    2  28/02/2015         India
21    Jeff    2   1/03/2015     Sri Lanka
22   David    2   1/03/2015      Pakistan
23  Raghav    2   3/03/2015  South Africa
24   David    2   4/03/2015      Pakistan
25  Ashley    2   4/03/2015     Australia
26    Jeff    2   5/03/2015    Bangladesh
27    Jeff    2   6/03/2015         India
28   David    2   7/03/2015      Pakistan
29  Ashley    2   7/03/2015       Ireland
30   David    2   8/03/2015   New Zealand
31  Ashley    2   8/03/2015     Australia
32    Jeff    2   9/03/2015    Bangladesh
33    Jeff    2  10/03/2015         India
34    Jeff    2  11/03/2015     Sri Lanka
35  Raghav    2  12/03/2015  South Africa
36   David    2  13/03/2015   New Zealand
37  Raghav    2  13/03/2015       England
38    Jeff    2  14/03/2015         India
39  Ashley    2  14/03/2015     Australia
40  Ashley    2  15/03/2015   West Indies
41   David    2  15/03/2015      Pakistan
42  Raghav    3  18/03/2015  South Africa
43  Ashley    3  19/03/2015     Australia
44    Jeff    3  20/03/2015         India
45   David    3  21/03/2015   New Zealand
46   David    3  24/03/2015   New Zealand
47  Ashley    3  26/03/2015     Australia
48     NaN    4  29/03/2015             ?
49    Jeff    1  21/02/2015    Bangladesh
50  Ashley    0  29/03/2015     Australia
51   David    0  29/03/2015   New Zealand
52    Jeff    0  29/03/2015         India
53  Raghav    0  29/03/2015  South Africa

In [195]:
import datetime as dt

dt_list = []
dtstr_list = []
for i, j in melted2['Start Date'].iteritems():
    dtl = dt.datetime.strptime(j, '%d/%m/%Y')
    dts = dt.datetime.strftime(dtl, '%m/%d/%Y')
    dtstr_list.append(dts)
    
    begin = dt.datetime(2015, 2, 14)
    diff = dtl - begin
    dt_list.append(diff.days)
    

melted2['start_date'] = dtstr_list
melted2['day_num'] = dt_list
melted2

     Owner  Pts  Start Date        winner  start_date  day_num
0    David    2  14/02/2015   New Zealand  02/14/2015        0
1   Ashley    2  14/02/2015     Australia  02/14/2015        0
2   Raghav    2  15/02/2015  South Africa  02/15/2015        1
3     Jeff    2  15/02/2015         India  02/15/2015        1
4   Ashley    2  16/02/2015       Ireland  02/16/2015        2
5    David    2  17/02/2015   New Zealand  02/17/2015        3
6     Jeff    2  18/02/2015    Bangladesh  02/18/2015        4
7    David    2  19/02/2015      Zimbabwe  02/19/2015        5
8    David    2  20/02/2015   New Zealand  02/20/2015        6
9   Ashley    2  21/02/2015   West Indies  02/21/2015        7
10  Ashley    1  21/02/2015     Australia  02/21/2015        7
11    Jeff    2  22/02/2015     Sri Lanka  02/22/2015        8
12    Jeff    2  22/02/2015         India  02/22/2015        8
13  Raghav    2  23/02/2015       England  02/23/2015        9
14  Ashley    2  24/02/2015   West Indies  02/24/2015       10
15  Ashley    2  25/02/2015       Ireland  02/25/2015       11
16   David    2  26/02/2015   Afghanistan  02/26/2015       12
17    Jeff    2  26/02/2015     Sri Lanka  02/26/2015       12
18  Raghav    2  27/02/2015  South Africa  02/27/2015       13
19   David    2  28/02/2015   New Zealand  02/28/2015       14
20    Jeff    2  28/02/2015         India  02/28/2015       14
21    Jeff    2   1/03/2015     Sri Lanka  03/01/2015       15
22   David    2   1/03/2015      Pakistan  03/01/2015       15
23  Raghav    2   3/03/2015  South Africa  03/03/2015       17
24   David    2   4/03/2015      Pakistan  03/04/2015       18
25  Ashley    2   4/03/2015     Australia  03/04/2015       18
26    Jeff    2   5/03/2015    Bangladesh  03/05/2015       19
27    Jeff    2   6/03/2015         India  03/06/2015       20
28   David    2   7/03/2015      Pakistan  03/07/2015       21
29  Ashley    2   7/03/2015       Ireland  03/07/2015       21
30   David    2   8/03/2015   New Zealand  03/08/2015       22
31  Ashley    2   8/03/2015     Australia  03/08/2015       22
32    Jeff    2   9/03/2015    Bangladesh  03/09/2015       23
33    Jeff    2  10/03/2015         India  03/10/2015       24
34    Jeff    2  11/03/2015     Sri Lanka  03/11/2015       25
35  Raghav    2  12/03/2015  South Africa  03/12/2015       26
36   David    2  13/03/2015   New Zealand  03/13/2015       27
37  Raghav    2  13/03/2015       England  03/13/2015       27
38    Jeff    2  14/03/2015         India  03/14/2015       28
39  Ashley    2  14/03/2015     Australia  03/14/2015       28
40  Ashley    2  15/03/2015   West Indies  03/15/2015       29
41   David    2  15/03/2015      Pakistan  03/15/2015       29
42  Raghav    3  18/03/2015  South Africa  03/18/2015       32
43  Ashley    3  19/03/2015     Australia  03/19/2015       33
44    Jeff    3  20/03/2015         India  03/20/2015       34
45   David    3  21/03/2015   New Zealand  03/21/2015       35
46   David    3  24/03/2015   New Zealand  03/24/2015       38
47  Ashley    3  26/03/2015     Australia  03/26/2015       40
48     NaN    4  29/03/2015             ?  03/29/2015       43
49    Jeff    1  21/02/2015    Bangladesh  02/21/2015        7
50  Ashley    0  29/03/2015     Australia  03/29/2015       43
51   David    0  29/03/2015   New Zealand  03/29/2015       43
52    Jeff    0  29/03/2015         India  03/29/2015       43
53  Raghav    0  29/03/2015  South Africa  03/29/2015       43

In [196]:
melted2.sort('day_num')
df3 = melted2.groupby(['Owner', 'day_num', 'start_date']).sum()
df3.to_csv('munged.csv')